export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  dbHost: process.env.DB_HOST ?? "127.0.0.1",
  dbPort: Number.parseInt(process.env.DB_PORT ?? "3306", 10),
  dbUser: process.env.DB_USER ?? "",
  dbPassword: process.env.DB_PASS ?? "",
  dbName: process.env.DB_NAME ?? "",
  dbSocketPath: process.env.MYSQL_UNIX_SOCKET ?? "",
  dbPoolLimit: Number.parseInt(process.env.DB_POOL_LIMIT ?? "5", 10),
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  vertexProjectId: (process.env.VERTEX_AI_PROJECT_ID ?? process.env.GOOGLE_CLOUD_PROJECT ?? "").trim(),
  vertexLocation: (process.env.VERTEX_AI_LOCATION ?? "global").trim(),
  vertexModel: (process.env.VERTEX_AI_MODEL ?? "gemini-2.5-flash").trim(),
  vertexImageLocation: (process.env.VERTEX_AI_IMAGE_LOCATION ?? "global").trim(),
  vertexImageModel: (process.env.VERTEX_AI_IMAGE_MODEL ?? "gemini-3.1-flash-image").trim(),
  gcsBucket: process.env.GCS_BUCKET ?? "",
  primaryAdminEmail: (process.env.PRIMARY_ADMIN_EMAIL ?? "info@nyccleaning.co").trim().toLowerCase(),
  resendApiKey: process.env.RESEND_API_KEY ?? "",
  resendFromEmail: process.env.RESEND_FROM_EMAIL?.trim() ?? "",
  googleMapsApiKey: process.env.GOOGLE_MAPS_API_KEY?.trim() ?? "",
  appBaseUrl: (process.env.APP_BASE_URL ?? "https://www.nyccleaning.co").replace(/\/$/, ""),
};
