export const brandAssets = {
  logo: "/manus-storage/nyc-cleaning-logo_aabc7372.webp",
  hero: "/manus-storage/nyc-cleaning-hero-v2_40f4e363.png",
  aboutTeam: "/manus-storage/nyc-cleaning-about-team-v2_9f9c83de.png",
  careers: "/manus-storage/nyc-cleaning-careers-v2_55866292.png",
  contact: "/manus-storage/nyc-cleaning-contact-v2_f579150a.png",
  serviceArea: "/manus-storage/nyc-cleaning-service-area-v2_f9738d26.png",
  commercialCleaning: "/manus-storage/nyc-cleaning-commercial-cleaning-v2_0203dcc6.png",
  deepCleaning: "/manus-storage/nyc-cleaning-deep-cleaning-v2_f503466f.png",
  commonArea: "/manus-storage/nyc-cleaning-common-area-v2_94e14b83.png",
  staffing: "/manus-storage/nyc-cleaning-staffing-v2_30b09bf9.png",
  houseCleaning: "/manus-storage/nyc-cleaning-house-cleaning-v2_07befc0d.png",
  propertyMaintenance: "/manus-storage/nyc-cleaning-property-maintenance-v2_6606af1d.png",
  repair: "/manus-storage/nyc-cleaning-repair-v2_920ec7b7.png",
  buildingMaintenance: "/manus-storage/nyc-cleaning-building-maintenance-v2_48d85e19.png",
  janitorial: "/manus-storage/nyc-cleaning-janitorial-v2_90b970d8.png",
  maintenanceManagement: "/manus-storage/nyc-cleaning-maintenance-management-v2_57ecbbe8.png",
  doorman: "/manus-storage/nyc-cleaning-doorman-v2_a294c98f.png",
  garbageBin: "/manus-storage/nyc-cleaning-garbage-bin-v2_e04ea805.png",
  officeCleaning: "/manus-storage/nyc-cleaning-office-cleaning-v2_9470169a.png",
  porter: "/manus-storage/nyc-cleaning-porter-v2_06cbeb37.png",
  apartmentCleaning: "/manus-storage/nyc-cleaning-apartment-cleaning-v2_6ad72f22.png",
  pricing: "/manus-storage/nyc-cleaning-pricing-v2_83d318af.png",
  propertyCleaning: "/manus-storage/nyc-cleaning-property-cleaning-v2_2b2acf31.png",
  sweepingTrash: "/manus-storage/nyc-cleaning-sweeping-trash-v2_d7cadf79.png",
} as const;

export type BrandAssetKey = keyof typeof brandAssets;
